# alias emacsdf="CWD=`pwd` docker-compose -f ~/Dop/docker_guiapps/emacs/docker-compose.yml run emacsdf" 'run emacs from current dir


version: '3.9'
services:
  emacsdf:
    image: "localhost/emacs"
    container_name: emacsdf
    hostname: "${BCWD}"
    command: emacs
    env_file: "/${CWD}/.goenv"
    environment:
      DISPLAY: "${DISPLAY}"
    devices:
      - /dev/snd
      - /dev/dri/card0
      # - /dev/hidraw5
    volumes:
      - /usr/share/fonts:/usr/share/fonts:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie

      - ./homedir:${HOME}:rw
      - ${HOME}/Govers/:${HOME}/Govers:rw
      - ${HOME}/Scripts/:${HOME}/Scripts:ro
      - ${CWD}/:${HOME}/Data/${BCWD}:rw
      - ${HOME}${USERPROFILE}/.netrc:/${HOME}.netrc
    working_dir: ${DCWD}
    # ports:
      # - "443:443"
